Repository Witiko/expltools, pull requests merged in 2025-02, with the labels that each got.

#46 Make various fixes
  CHANGES.md
  README.md
  explcheck/doc/warnings-and-errors-02-lexical-analysis.md
  explcheck/src/explcheck-cli.lua
  explcheck/src/explcheck-format.lua
  explcheck/src/explcheck-issues.lua
  explcheck/src/explcheck-lexical-analysis.lua
  explcheck/src/explcheck-parsers.lua
  explcheck/src/explcheck-preprocessing.lua
  explcheck/testfiles/s103.tex
  explcheck/testfiles/w200.lua
  explcheck/testfiles/w200.tex
Labels: bug

#43 Exclude comments from maximum line length checks
  CHANGES.md
  explcheck/src/explcheck-format.lua
  explcheck/src/explcheck-parsers.lua
  explcheck/src/explcheck-preprocessing.lua
  explcheck/testfiles/s103.tex
Labels: bug

#44 Always accept both lower- and upper-case issue identifiers
  CHANGES.md
  README.md
  explcheck/src/explcheck-cli.lua
  explcheck/src/explcheck-issues.lua
  explcheck/src/explcheck-parsers.lua
Labels: bug

#45 Exclude "weird" (`:w`) argument specifiers from warning W200
  CHANGES.md
  explcheck/doc/warnings-and-errors-02-lexical-analysis.md
  explcheck/src/explcheck-lexical-analysis.lua
  explcheck/src/explcheck-parsers.lua
  explcheck/testfiles/w200.lua
  explcheck/testfiles/w200.tex
Labels: bug

#48 Add `explcheck-ranges.lua`
  CHANGES.md
  explcheck/src/explcheck-format.lua
  explcheck/src/explcheck-issues.lua
  explcheck/src/explcheck-lexical-analysis.lua
  explcheck/src/explcheck-preprocessing.lua
  explcheck/src/explcheck-ranges.lua
  explcheck/testfiles/e102-03.lua
  explcheck/testfiles/e102.lua
  explcheck/testfiles/e104.lua
  explcheck/testfiles/e201.lua
  explcheck/testfiles/e203.lua
  explcheck/testfiles/e208.lua
  explcheck/testfiles/e209.lua
  explcheck/testfiles/s103.lua
  explcheck/testfiles/s204.lua
  explcheck/testfiles/s205-01.lua
  explcheck/testfiles/s205-02.lua
  explcheck/testfiles/s205-03.lua
  explcheck/testfiles/s206-01.lua
  explcheck/testfiles/s207-01.lua
  explcheck/testfiles/s207-03.lua
  explcheck/testfiles/w101.lua
  explcheck/testfiles/w200.lua
  explcheck/testfiles/w202.lua
Labels: housekeeping

#50 Add SPDX Identifier
  CHANGES.md
  README.md
Labels: documentation

#52 Continuously run explcheck on all packages in historical TeX Live Docker images
  .explcheckrc
  .github/workflows/main.yml
  CHANGES.md
  explcheck/src/explcheck-cli.lua
  explcheck/src/explcheck-lexical-analysis.lua
  explcheck/src/explcheck-preprocessing.lua
  explcheck/testfiles/TL2013-errors.txt.gz
  explcheck/testfiles/TL2014-errors.txt.gz
  explcheck/testfiles/TL2015-errors.txt.gz
  explcheck/testfiles/TL2016-errors.txt.gz
  explcheck/testfiles/TL2017-errors.txt.gz
  explcheck/testfiles/TL2018-errors.txt.gz
  explcheck/testfiles/TL2019-errors.txt.gz
  explcheck/testfiles/TL2020-errors.txt.gz
  explcheck/testfiles/TL2021-errors.txt.gz
  explcheck/testfiles/TL2022-errors.txt.gz
  explcheck/testfiles/TL2023-errors.txt.gz
Labels: bug, enhancement

#54 Remove error E203 (Removed control sequences)
  .github/workflows/main.yml
  CHANGES.md
  explcheck/doc/e203.tex
  explcheck/doc/warnings-and-errors-02-lexical-analysis.md
  explcheck/src/explcheck-lexical-analysis.lua
  explcheck/src/generate-explcheck-obsolete.lua
  explcheck/support/markdownthemewitiko_expltools_explcheck_warnings-and-errors.sty
  explcheck/testfiles/TL2013-errors.txt.gz
  explcheck/testfiles/TL2014-errors.txt.gz
  explcheck/testfiles/TL2015-errors.txt.gz
  explcheck/testfiles/TL2016-errors.txt.gz
  explcheck/testfiles/TL2017-errors.txt.gz
  explcheck/testfiles/TL2018-errors.txt.gz
  explcheck/testfiles/TL2019-errors.txt.gz
  explcheck/testfiles/TL2020-errors.txt.gz
  explcheck/testfiles/TL2021-errors.txt.gz
  explcheck/testfiles/TL2022-errors.txt.gz
  explcheck/testfiles/TL2023-errors.txt.gz
  explcheck/testfiles/e203.lua
  explcheck/testfiles/e203.tex
Labels: bug

#59 Assert that `commented_lines` always matches the whole file content
  CHANGES.md
  explcheck/src/explcheck-parsers.lua
  explcheck/src/explcheck-preprocessing.lua
Labels: bug

#60 Do not recognize `@` as a part of an expl3 control sequence
  CHANGES.md
  explcheck/src/explcheck-parsers.lua
  explcheck/testfiles/TL2013-issues.txt
  explcheck/testfiles/TL2014-issues.txt
  explcheck/testfiles/TL2015-issues.txt
  explcheck/testfiles/TL2016-issues.txt
  explcheck/testfiles/TL2017-issues.txt
  explcheck/testfiles/TL2018-issues.txt
  explcheck/testfiles/TL2019-issues.txt
  explcheck/testfiles/TL2020-issues.txt
  explcheck/testfiles/TL2021-issues.txt
  explcheck/testfiles/TL2022-issues.txt
  explcheck/testfiles/TL2023-issues.txt
  explcheck/update-regression-tests.sh
Labels: bug

#61 Add CLI option `--make-at-letter` and Lua option `make_at_letter`
  .github/workflows/main.yml
  CHANGES.md
  README.md
  explcheck/src/explcheck-cli.lua
  explcheck/src/explcheck-config.lua
  explcheck/src/explcheck-lexical-analysis.lua
  explcheck/src/explcheck-parsers.lua
  explcheck/src/explcheck-preprocessing.lua
  explcheck/src/explcheck-utils.lua
  explcheck/testfiles/TL2014-issues.txt
  explcheck/testfiles/TL2015-issues.txt
  explcheck/testfiles/TL2016-issues.txt
  explcheck/testfiles/TL2017-issues.txt
  explcheck/testfiles/TL2018-issues.txt
  explcheck/testfiles/TL2019-issues.txt
  explcheck/testfiles/TL2020-issues.txt
  explcheck/testfiles/TL2021-issues.txt
  explcheck/testfiles/TL2022-issues.txt
  explcheck/testfiles/TL2023-issues.txt
  explcheck/testfiles/e102-01.lua
  explcheck/testfiles/e102-02.lua
  explcheck/testfiles/e102-03.lua
  explcheck/testfiles/e102.lua
  explcheck/testfiles/e104.lua
  explcheck/testfiles/e201.lua
  explcheck/testfiles/e208.lua
  explcheck/testfiles/e209.lua
  explcheck/testfiles/s103.lua
  explcheck/testfiles/s204.lua
  explcheck/testfiles/s205-01.lua
  explcheck/testfiles/s205-02.lua
  explcheck/testfiles/s205-03.lua
  explcheck/testfiles/s205-04.lua
  explcheck/testfiles/s206-01.lua
  explcheck/testfiles/s206-02.lua
  explcheck/testfiles/s206-03.lua
  explcheck/testfiles/s207-01.lua
  explcheck/testfiles/s207-02.lua
  explcheck/testfiles/s207-03.lua
  explcheck/testfiles/s207-04.lua
  explcheck/testfiles/w100-01.lua
  explcheck/testfiles/w100-02.lua
  explcheck/testfiles/w100-03.lua
  explcheck/testfiles/w100.lua
  explcheck/testfiles/w101.lua
  explcheck/testfiles/w200.lua
  explcheck/testfiles/w202.lua
Labels: enhancement

#63 Pre-configure all remaining expl3 package files
  CHANGES.md
  explcheck/src/explcheck-cli.lua
  explcheck/src/explcheck-config.lua
  explcheck/src/explcheck-config.toml
  explcheck/src/explcheck-preprocessing.lua
  explcheck/testfiles/TL2013-issues.txt
  explcheck/testfiles/TL2014-issues.txt
  explcheck/testfiles/TL2015-issues.txt
  explcheck/testfiles/TL2016-issues.txt
  explcheck/testfiles/TL2017-issues.txt
  explcheck/testfiles/TL2018-issues.txt
  explcheck/testfiles/TL2019-issues.txt
  explcheck/testfiles/TL2020-issues.txt
  explcheck/testfiles/TL2021-issues.txt
  explcheck/testfiles/TL2022-issues.txt
  explcheck/testfiles/TL2023-issues.txt
Labels: bug

#64 Stabilize the Lua API of processing steps
  CHANGES.md
  README.md
  explcheck/src/explcheck-cli.lua
  explcheck/src/explcheck-config.lua
  explcheck/src/explcheck-lexical-analysis.lua
  explcheck/src/explcheck-preprocessing.lua
  explcheck/testfiles/e102-01.lua
  explcheck/testfiles/e102-02.lua
  explcheck/testfiles/e102-03.lua
  explcheck/testfiles/e102.lua
  explcheck/testfiles/e104.lua
  explcheck/testfiles/e201.lua
  explcheck/testfiles/e208.lua
  explcheck/testfiles/e209.lua
  explcheck/testfiles/s103.lua
  explcheck/testfiles/s204.lua
  explcheck/testfiles/s205-01.lua
  explcheck/testfiles/s205-02.lua
  explcheck/testfiles/s205-03.lua
  explcheck/testfiles/s205-04.lua
  explcheck/testfiles/s206-01.lua
  explcheck/testfiles/s206-02.lua
  explcheck/testfiles/s206-03.lua
  explcheck/testfiles/s207-01.lua
  explcheck/testfiles/s207-02.lua
  explcheck/testfiles/s207-03.lua
  explcheck/testfiles/s207-04.lua
  explcheck/testfiles/w100-01.lua
  explcheck/testfiles/w100-02.lua
  explcheck/testfiles/w100-03.lua
  explcheck/testfiles/w100.lua
  explcheck/testfiles/w101.lua
  explcheck/testfiles/w200.lua
  explcheck/testfiles/w202.lua
Labels: enhancement
